dummy: dummy.o data/basic_cmds.o
	ld -g dummy.o data/basic_cmds.o -o dummy
dummy.o: dummy.s
	as -g dummy.s -o dummy.o
calc.o: calc.s
	as -g calc.s -o calc.o
basic_cmds.o: data/basic_cmds.s
	as -g data/basic_cmds.s -o data/basic_cmds.o
calc_basic: and.o or.o sum.o calc.o data/basic_cmds.o upper.o
	ld -g and.o or.o sum.o calc.o data/basic_cmds.o upper.o -o calc_basic
and.o: and.s
	as -g and.s -o and.o
or.o: or.s
	as -g or.s -o or.o
sum.o: sum.s
	as -g sum.s -o sum.o
upper.o: upper.s
	as -g upper.s -o upper.o
calc_simplerandom: and.o or.o sum.o calc.o upper.o data/simplerandom_cmds.o
	ld -g and.o or.o sum.o calc.o upper.o data/simplerandom_cmds.o -o calc_simplerandom
calc_upperonly: and.o or.o sum.o calc.o upper.o data/upperonly_cmds.o
	ld -g and.o or.o sum.o calc.o upper.o data/upperonly_cmds.o -o calc_upperonly
calc_easy: and.o or.o sum.o calc.o upper.o data/easy_cmds.o
	ld -g and.o or.o sum.o calc.o upper.o data/easy_cmds.o -o calc_easy
calc_basicwithupper: and.o or.o sum.o calc.o upper.o data/basicwithupper_cmds.o
	ld -g and.o or.o sum.o calc.o upper.o data/basicwithupper_cmds.o -o calc_basicwithupper
calc_simpleone: and.o or.o sum.o calc.o upper.o data/simpleone_cmds.o
	ld -g and.o or.o sum.o calc.o upper.o data/simpleone_cmds.o -o calc_simpleone